version: '2.3'

services:

  # During development we want to build our Docker image from relevant
  # Dockerfiles, as opposed to pulling it from a repository somewhere.

  lab:
    build: 
      context: notebooks
      dockerfile: composer/Dockerfile
    volumes:
      - ./assessment:/dli/task/assessment

  llm_client:
    build:
      context: notebooks/composer/microservices
      dockerfile: llm_client.Dockerfile
    environment:
      - DEBUG=1
    env_file:
      - .env-dev  ## NVIDIA_API_KEY
  
  docker_router:
    build:
      context: notebooks/composer/microservices
      dockerfile: docker_router.Dockerfile

  nginx:
    ports:
      - $DEV_NGINX_PORT:80

  assessment:
    ports:
      - $DEV_ASSESSMENT_PORT:8080

  # nim:
  #   env_file:
  #     - .env-dev  ## NGC_API_KEY

  # embedding:
  #   env_file:
  #     - .env-dev  ## NGC_API_KEY

  # ranking:
  #   env_file:
  #     - .env-dev  ## NGC_API_KEY

  ddg-cache:
    container_name: ddg-cache
    build:
      context: ./notebooks/composer/microservices
      dockerfile: ddg_dockerfile.Dockerfile

  lg_viz:
    build: notebooks/composer/microservices/lg_viz
